# Generated by Django 3.1.1 on 2020-10-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpiapp', '0002_auto_20201005_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default='no_img.jpg', upload_to='profile picture'),
        ),
    ]
