# Generated by Django 3.1.1 on 2020-10-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpiapp', '0003_studentprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student',
            new_name='user',
        ),
    ]
