# Generated by Django 3.1.1 on 2020-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpiapp', '0006_auto_20201006_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
