# Generated by Django 3.1.1 on 2020-10-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpiapp', '0008_auto_20201006_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ComplaintForm',
            new_name='Complaint',
        ),
    ]
