# Generated by Django 3.1.1 on 2020-10-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpiapp', '0010_auto_20201007_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
