# Generated by Django 3.1.1 on 2020-10-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpiapp', '0012_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
